version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
  celery:
    build: .
    command: celery -A rss_scraper worker -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - rabbit
    env_file:
      - ./.env.dev
  rabbit:
    image: rabbitmq:3
    ports:
      - 5672:5672

  celery-beat:
    build: .
    command: celery -A rss_scraper beat -l info
    volumes:
      - .:/app
    depends_on:
      - rabbit
    env_file:
      - ./.env.dev

volumes:
  postgres_data:
