version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod

  rabbit:
    image: rabbitmq:3
    ports:
      - 5672:5672

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/home/app/web/staticfiles
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: bash -c 'python manage.py makemigrations && python manage.py migrate && gunicorn rss_scraper.wsgi:application --bind 0.0.0.0:8000'
    container_name: app
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  celery:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    command: celery -A rss_scraper worker -l info
    volumes:
      - .:/app
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - rabbit

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: celery -A rss_scraper beat -l info
    volumes:
      - .:/app
    depends_on:
      - rabbit
    env_file:
      - ./.env.prod

volumes:
  postgres_data:
  static_volume:
